channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pytorch=1.13.*=*cuda* # Need to specifically request cuda version
  - torchvision=0.14.*
  - ipykernel=6.29.*
  - pip>=23
